### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined 

### ISSUE THREAD

**Issue by peterduyts** [rthewhite/homebridge-homewizard#62]
After installing HB-HW , I immediatly run into this error.  

I tried to filter the scenes (like the Timer Plinten in the log) but to no avail

The HB does not become visible on the network. 

Platform : OSX Sierra

Tried on another Mac, but have the same problem.  In the homebridge I also use a Harmony hub, that works fine so I assume the NodeJS and Homebridge installation is OK  

Does anyone have any idea what the problem could be ?   

Log :   

[8/15/2017, 3:04:25 PM] [HomeWizard] Initializing platform accessory 'Timer plinten'...
[8/15/2017, 3:04:25 PM] [HomeWizard] Failed to retrieve accessories from HomeWizard
[8/15/2017, 3:04:25 PM] [HomeWizard] TypeError: Cannot read property 'length' of undefined
    at Characteristic.validateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:225:19)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:273:19)
    at Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:173:32)
    at HomeWizardScene._setupInformationService (/usr/local/lib/node_modules/homebridge-homewizard/dist/accessories/accessory.js:39:162)
    at HomeWizardScene.getServices (/usr/local/lib/node_modules/homebridge-homewizard/dist/accessories/accessory.js:57:12)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:378:36)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:364:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/local/lib/node_modules/homebridge-homewizard/dist/platform.js:72:9
    at _fulfilled (/usr/local/lib/node_modules/homebridge-homewizard/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/homebridge-homewizard/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/homebridge-homewizard/node_modules/q/q.js:816:13)
    at /usr/local/lib/node_modules/homebridge-homewizard/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/homebridge-homewizard/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/homebridge-homewizard/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by peterduyts** [comment]
Solved it by using a raspberry Pi ;)
