### ISSUE TITLE
error at launch : lost all devices homewizard

### ISSUE THREAD

**Issue by jeyremy** [rthewhite/homebridge-homewizard#75]
Hi, 
first of all thank you for this awesome plugin i use it every day for the past 6 month.

Now my "little" issue : my mac is rebooting every night arround 3:30AM and for some time when it comes back up and launch homebridge it's like it can't comunicate with homewizard so the morning in home app, i have lost all homewizard devices. (but other hombridge device are still here and working)
then i reboot homebridge and all my homewizard devices comes back but like new devices so i have to re-do all my scenes, and room association. 

i contact you beacause it's the second day in a row now... :) 

here's an error log  :

`Unhandled rejection RequestError: Error: connect ENETUNREACH 192.168.1.35:8563 - Local (0.0.0.0:49154)
    at new RequestError (/usr/local/lib/node_modules/homebridge-homewizard/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-homewizard/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/usr/local/lib/node_modules/homebridge-homewizard/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-homewizard/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Unhandled rejection RequestError: Error: connect ENETUNREACH 192.168.1.35:8563 - Local (0.0.0.0:49155)
    at new RequestError (/usr/local/lib/node_modules/homebridge-homewizard/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-homewizard/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/usr/local/lib/node_modules/homebridge-homewizard/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)`

**Comment by rthewhite** [comment]
The problem is in the fact that the plugin can't reach your HomeWizard during startup. Seems like a network related issue. Maybe your wifi is not connected yet during startup for example? 

The plugin should handle this a bit more gracefully then it does now. But as stated in the readme, I'm not supporting the plugin anymore since i don't have a HomeWizard anymore. And don't even use homebridge at all anymore. So unless someone picks this up, you will have to work around it somehow.

**Comment by jeyremy** [comment]
Hi, 
Thanks for your response, it's exactly what you said, my homebridge process was launched before end of network at boot.

But, i have seen some other plugins do the exact same think exept that accessories was not deleted, 
just a red "no response" under the accessories... 

i'm a dev, but unexpereimented on node.js so i will fork the project and see if i can do something but it seem a little too complicated for me right now... :) 

if someone can help me... :)

**Comment by jeyremy** [comment]
I'm crying ! 
i have all lost, again... now i have to re-do all my scenes
it's realy a shame because the plugin work perfectly exept for that...  

can you give me some advice for helping maintain the project ?  

thanks
